baseURL = "https://secondwind.nz/photos"

# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]

defaultContentLanguage = "en"

# The name of this wonderful theme ;-).
theme = "gallery"

# The browser tab name
title = "Second Wind Photos"

# In order to add version information in the page's footer set to true.
# enableGitInfo = true

contentDir = "content/photos"
publishDir = "public/photos"
staticDir = "static/photos"